
    <html lang="zh-cn">
    <head>
    <meta content="text/html; charset=utf-8" http-equiv="content-type" />
    <link href="../../../../default.css" rel="stylesheet">
    <link href="
   ../../../../github.css" rel="stylesheet">
    </head>
    <body>
    <div itemscope itemtype="http://developers.google.com/ReferenceObject">
<meta itemprop="name" content="tf.compat.v1.errors" />
<meta itemprop="path" content="Stable" />
<meta itemprop="property" content="ABORTED"/>
<meta itemprop="property" content="ALREADY_EXISTS"/>
<meta itemprop="property" content="CANCELLED"/>
<meta itemprop="property" content="DATA_LOSS"/>
<meta itemprop="property" content="DEADLINE_EXCEEDED"/>
<meta itemprop="property" content="FAILED_PRECONDITION"/>
<meta itemprop="property" content="INTERNAL"/>
<meta itemprop="property" content="INVALID_ARGUMENT"/>
<meta itemprop="property" content="NOT_FOUND"/>
<meta itemprop="property" content="OK"/>
<meta itemprop="property" content="OUT_OF_RANGE"/>
<meta itemprop="property" content="PERMISSION_DENIED"/>
<meta itemprop="property" content="RESOURCE_EXHAUSTED"/>
<meta itemprop="property" content="UNAUTHENTICATED"/>
<meta itemprop="property" content="UNAVAILABLE"/>
<meta itemprop="property" content="UNIMPLEMENTED"/>
<meta itemprop="property" content="UNKNOWN"/>
</div>

<h1 id="module-tfcompatv1errors">Module: tf.compat.v1.errors</h1>
<table class="tfo-notebook-buttons tfo-api" align="left">
</table>

<p>Exception types for TensorFlow errors.</p>
<h2 id="classes">Classes</h2>
<p><a href="../../../tf/errors/AbortedError.html"><code>class AbortedError</code></a>: The operation was aborted, typically due to a concurrent action.</p>
<p><a href="../../../tf/errors/AlreadyExistsError.html"><code>class AlreadyExistsError</code></a>: Raised when an entity that we attempted to create already exists.</p>
<p><a href="../../../tf/errors/CancelledError.html"><code>class CancelledError</code></a>: Raised when an operation or step is cancelled.</p>
<p><a href="../../../tf/errors/DataLossError.html"><code>class DataLossError</code></a>: Raised when unrecoverable data loss or corruption is encountered.</p>
<p><a href="../../../tf/errors/DeadlineExceededError.html"><code>class DeadlineExceededError</code></a>: Raised when a deadline expires before an operation could complete.</p>
<p><a href="../../../tf/errors/FailedPreconditionError.html"><code>class FailedPreconditionError</code></a>: Operation was rejected because the system is not in a state to execute it.</p>
<p><a href="../../../tf/errors/InternalError.html"><code>class InternalError</code></a>: Raised when the system experiences an internal error.</p>
<p><a href="../../../tf/errors/InvalidArgumentError.html"><code>class InvalidArgumentError</code></a>: Raised when an operation receives an invalid argument.</p>
<p><a href="../../../tf/errors/NotFoundError.html"><code>class NotFoundError</code></a>: Raised when a requested entity (e.g., a file or directory) was not found.</p>
<p><a href="../../../tf/errors/OpError.html"><code>class OpError</code></a>: A generic error that is raised when TensorFlow execution fails.</p>
<p><a href="../../../tf/errors/OutOfRangeError.html"><code>class OutOfRangeError</code></a>: Raised when an operation iterates past the valid input range.</p>
<p><a href="../../../tf/errors/PermissionDeniedError.html"><code>class PermissionDeniedError</code></a>: Raised when the caller does not have permission to run an operation.</p>
<p><a href="../../../tf/errors/ResourceExhaustedError.html"><code>class ResourceExhaustedError</code></a>: Some resource has been exhausted.</p>
<p><a href="../../../tf/errors/UnauthenticatedError.html"><code>class UnauthenticatedError</code></a>: The request does not have valid authentication credentials.</p>
<p><a href="../../../tf/errors/UnavailableError.html"><code>class UnavailableError</code></a>: Raised when the runtime is currently unavailable.</p>
<p><a href="../../../tf/errors/UnimplementedError.html"><code>class UnimplementedError</code></a>: Raised when an operation has not been implemented.</p>
<p><a href="../../../tf/errors/UnknownError.html"><code>class UnknownError</code></a>: Unknown error.</p>
<p><a href="../../../tf/compat/v1/errors/raise_exception_on_not_ok_status.html"><code>class raise_exception_on_not_ok_status</code></a>: Context manager to check for C API status.</p>
<h2 id="functions">Functions</h2>
<p><a href="../../../tf/compat/v1/errors/error_code_from_exception_type.html"><code>error_code_from_exception_type(...)</code></a></p>
<p><a href="../../../tf/compat/v1/errors/exception_type_from_error_code.html"><code>exception_type_from_error_code(...)</code></a></p>
<h2 id="other-members">Other Members</h2>
<ul>
<li><code>ABORTED = 10</code> <a id="ABORTED"></a></li>
<li><code>ALREADY_EXISTS = 6</code> <a id="ALREADY_EXISTS"></a></li>
<li><code>CANCELLED = 1</code> <a id="CANCELLED"></a></li>
<li><code>DATA_LOSS = 15</code> <a id="DATA_LOSS"></a></li>
<li><code>DEADLINE_EXCEEDED = 4</code> <a id="DEADLINE_EXCEEDED"></a></li>
<li><code>FAILED_PRECONDITION = 9</code> <a id="FAILED_PRECONDITION"></a></li>
<li><code>INTERNAL = 13</code> <a id="INTERNAL"></a></li>
<li><code>INVALID_ARGUMENT = 3</code> <a id="INVALID_ARGUMENT"></a></li>
<li><code>NOT_FOUND = 5</code> <a id="NOT_FOUND"></a></li>
<li><code>OK = 0</code> <a id="OK"></a></li>
<li><code>OUT_OF_RANGE = 11</code> <a id="OUT_OF_RANGE"></a></li>
<li><code>PERMISSION_DENIED = 7</code> <a id="PERMISSION_DENIED"></a></li>
<li><code>RESOURCE_EXHAUSTED = 8</code> <a id="RESOURCE_EXHAUSTED"></a></li>
<li><code>UNAUTHENTICATED = 16</code> <a id="UNAUTHENTICATED"></a></li>
<li><code>UNAVAILABLE = 14</code> <a id="UNAVAILABLE"></a></li>
<li><code>UNIMPLEMENTED = 12</code> <a id="UNIMPLEMENTED"></a></li>
<li><code>UNKNOWN = 2</code> <a id="UNKNOWN"></a></li>
</ul>
    </body>
    </html>
   